---
openapi: 3.0.1
info:
  title: Member Service
  version: v0
servers:
- url: http://localhost:49823
  description: Generated server url
paths:
  /members:
    get:
      tags:
      - member
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Member'
              examples:
                Full return of members.:
                  summary: All Members
                  description: Full return of members.
                  value:
                  - id: 1
                    firstName: Jessica
                    lastName: Campbell
                    email: jcampbell2i@cpanel.net
                  - id: 2
                    firstName: Bob
                    lastName: Marley
                    email: bob.marley@google.com
                  - id: 3
                    firstName: Tom
                    lastName: Brady
                    email: tom.brady@expat.net
          description: OK
      operationId: getAllMembers
      summary: Get all members and their information.
      description: Gets all members.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        required: true
      tags:
      - member
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: Created
        "400":
          content:
            text/plain: {}
          description: "Invalid input for member. firstName, lastName and email required."
      operationId: createMember
      summary: Save a new member or update an existing.
      description: Save a new member if doesnt exist or updates existing.
  /members/{id}:
    summary: REST API for basic member data.  member-service
    get:
      tags:
      - member
      parameters:
      - name: id
        description: Member id
        schema:
          format: int64
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
              examples:
                Member Example 1:
                  description: Member Example 1
                  value:
                    id: 1
                    firstName: Jessica
                    lastName: Campbell
                    email: jcampbell2i@cpanel.net
                Member Example 2:
                  description: Member Example 2
                  value:
                    id: 2
                    firstName: Bob
                    lastName: Marley
                    email: bob.marley@google.com
                Member Example 3:
                  description: Member Example 3
                  value:
                    id: 3
                    firstName: Tom
                    lastName: Brady
                    email: tom.brady@expat.net
          description: OK
        "400":
          content:
            text/plain: {}
          description: Invalid input. upcNbr required.
        "404":
          content:
            text/plain: {}
          description: Member with such upcNbr doesn't exists.
      operationId: getMember
      summary: Get a member information
      description: Returns a given member information given upcNbr for member.
    delete:
      tags:
      - member
      parameters:
      - name: id
        schema:
          format: int64
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            text/plain: {}
          description: Member was deleted.
      operationId: deleteMember
      summary: Deletes an member for given id.
      description: Deletes anmember for a given id.
components:
  schemas:
    Member:
      required:
      - email
      - firstName
      - lastName
      type: object
      properties:
        id:
          format: int64
          description: |-
            Member ID which is unique to a member. Is generated by service
            on creation.
          type: integer
          example: 1001
        firstName:
          description: First Name of Member
          maxLength: 50
          type: string
          example: Jessica
        lastName:
          description: Last Name of Member
          maxLength: 50
          type: string
          example: Campbell
        email:
          description: Email address of Member
          maxLength: 50
          pattern: .+@.+\..+
          type: string
          example: jcampbell2i@cpanel.net
tags:
- name: member
  description: '`Members` endpoints for Member information'
